### PR TITLE
updated and renamed migration file and seeder files according to orde…

### PR DESCRIPTION
**Pull request by mcoindreau**
…r of preference

### CODE REVIEW

**Comment by mcoindreau** [comment]
awaiting review

**Review by fmendozaro — CHANGES_REQUESTED** [review]
If 01-adlister-table-migration.sql is the first one i think it's missing a create db if exists statement.

**Review by fmendozaro — APPROVED** [review]
The create table works now.

**Comment by fmendozaro** [comment]
Fixes #30

**Pull request merged**
